"""empty message

Revision ID: 9672b252c3f5
Revises: dffa8a83949b
Create Date: 2019-12-16 17:18:16.880328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9672b252c3f5'
down_revision = 'dffa8a83949b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('genre_id')
    )
    op.add_column(u'Artist', sa.Column('genre_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Artist', 'genre', ['genre_id'], ['genre_id'])
    op.drop_column(u'Artist', 'genres')
    op.add_column(u'Venue', sa.Column('genre_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Venue', 'genre', ['genre_id'], ['genre_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column(u'Venue', 'genre_id')
    op.add_column(u'Artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    op.drop_column(u'Artist', 'genre_id')
    op.drop_table('genre')
    # ### end Alembic commands ###
